environment:
  ANACONDA_TOKEN:
    secure: IHuV8pqZulsweCS/2VLZNkJN3Vv0c23Cr6Yiudf/O8u/5IEU31qKLRbsqbKSj7Ez
  TWINE_PASSWORD:
    secure: 20R+TzZ9NRmt9ttc5/Bb8w==

  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      platform: x64
      DEPENDENCIES: "stable"
      PYPI_UPLOAD_SOURCE: "no"
      ANACONDA_UPLOAD: "yes"
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      platform: x64
      DEPENDENCIES: "stable"
      ANACONDA_UPLOAD: "no"
      PYPI_UPLOAD_SOURCE: "yes"
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      platform: x64
      DEPENDENCIES: "latest"
      ANACONDA_UPLOAD: "no"
      PYPI_UPLOAD_SOURCE: "no"
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      platform: x64
      DEPENDENCIES: "latest"
      ANACONDA_UPLOAD: "no"
      PYPI_UPLOAD_SOURCE: "no"
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      platform: x64
      DEPENDENCIES: "latest"
      ANACONDA_UPLOAD: "no"
      PYPI_UPLOAD_SOURCE: "no"
      FLOAT_DTYPE_32: "yes"
matrix:
  allow_failures:
    - DEPENDENCIES: "latest"

install:
  # Add the paths for anaconda
  - 'set PATH=%PYTHON%;%PYTHON%\Library\bin;%PYTHON%\Scripts;%PATH%'
  - 'echo %PATH%'
  # Update conda itself
  - 'conda update --yes --quiet conda'
  # Activate the conda environment
  - 'conda activate'
  # Install Brian 2 and dependencies
  - 'conda install --yes --quiet -c conda-forge brian2 sympy=1.1 py-cpuinfo=3 nose'
  # For "latest" dependencies, install Brian 2 from github
  - 'if  "%DEPENDENCIES%" == "latest" (
      conda uninstall --yes --quiet brian2 &&
      pip install git+https://github.com/brian-team/brian2.git)'
  # Install GeNN
  - 'cd ..'
  - 'git clone --depth=1 https://github.com/genn-team/genn.git'
  - if "%DEPENDENCIES%" == "stable" (cd genn && for /f %%a in ('git describe --tags --abbrev^=0 origin/master') do git checkout %%a && cd ..)
  - 'set GENN_PATH=%CD%\genn'
  - 'cd brian2genn'

build: false  # not a C# project

test_script:
  - 'pip install .'
  - 'if "%FLOAT_DTYPE_32%" == "yes" (python scripts/run_brian_tests_CPU_32bit.py) else (python scripts/run_brian_tests_CPU.py)'
