environment:
  ANACONDA_TOKEN:
    secure: IHuV8pqZulsweCS/2VLZNkJN3Vv0c23Cr6Yiudf/O8u/5IEU31qKLRbsqbKSj7Ez
  TWINE_PASSWORD:
    secure: 20R+TzZ9NRmt9ttc5/Bb8w==

  matrix:
    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_VERSION: "2.7"
      PYTHON_ARCH: "64"
      platform: x64
      DEPENDENCIES: "latest"
      ANACONDA_UPLOAD: "no"
      PYPI_UPLOAD_SOURCE: "no"
      FLOAT_DTYPE_32: "yes"
matrix:
  allow_failures:
    - DEPENDENCIES: "latest"

install:
  # Add the paths for anaconda
  - 'set PATH=%PYTHON%;%PYTHON%\Library\bin;%PYTHON%\Scripts;%PATH%'
  - 'echo %PATH%'
  # Update conda itself
  - 'conda update --yes --quiet conda'
  # Activate the conda environment
  - 'conda activate'
  # Install Brian 2 and dependencies
  - 'conda install --yes --quiet -c conda-forge sympy=1.1 py-cpuinfo=3 nose pip setuptools'
  - 'conda install --yes --quiet -c conda-forge --only-deps brian2'
  - 'pip install https://github.com/brian-team/brian2/archive/master.zip'
  # Install GeNN
  - # Clone the GeNN submodule
  - 'git submodule update --init --recursive'
  - 'if "%DEPENDENCIES%" == "latest" (cd genn && git checkout master && cd ..)'
  - 'set GENN_PATH=%CD%\genn'

build: false  # not a C# project

test_script:
  - 'pip install .'
  - 'python examples/simple_example.py'
