package:
  name: brian2genn
  version: "{{ load_setup_py_data().get('version') }}"

source:
  path: ..

build:
  number: 1
  script_env:
    - CUDA_PATH
    - PROCESSOR_ARCHITEW6432  # [win]
    - PROCESSOR_ARCHITECTURE  # [win]
    - PROCESSOR_IDENTIFIER  # [win]

requirements:
  build:
    - python
    - setuptools
    - gcc  # [linux]
  run:
    - brian2 >=2.0
    - python
    - gcc  # [linux]

about:
  home: http://github.com/brian-team/brian2genn
  license: GPL
  license_file: LICENSE
  summary: 'Brian 2 frontend to the GeNN simulator'
  doc_url: http://brian2genn.readthedocs.io/
  dev_url: http://github.com/brian-team/brian2genn
